<?php
namespace Jsvrcek\ICS\Tests\Model;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2013-10-20 at 12:03:54.
 */
class CalendarEvent extends \PHPUnit_Framework_TestCase
{
    /**
     * @var CalendarEvent
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new CalendarEvent;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Jsvrcek\ICS\Model\CalendarEvent::getUid
     * @todo   Implement testGetUid().
     */
    public function testGetUid()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Jsvrcek\ICS\Model\CalendarEvent::setUid
     * @todo   Implement testSetUid().
     */
    public function testSetUid()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Jsvrcek\ICS\Model\CalendarEvent::getStart
     * @todo   Implement testGetStart().
     */
    public function testGetStart()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Jsvrcek\ICS\Model\CalendarEvent::setStart
     * @todo   Implement testSetStart().
     */
    public function testSetStart()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Jsvrcek\ICS\Model\CalendarEvent::getEnd
     * @todo   Implement testGetEnd().
     */
    public function testGetEnd()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Jsvrcek\ICS\Model\CalendarEvent::setEnd
     * @todo   Implement testSetEnd().
     */
    public function testSetEnd()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Jsvrcek\ICS\Model\CalendarEvent::getSummary
     * @todo   Implement testGetSummary().
     */
    public function testGetSummary()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Jsvrcek\ICS\Model\CalendarEvent::setSummary
     * @todo   Implement testSetSummary().
     */
    public function testSetSummary()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Jsvrcek\ICS\Model\CalendarEvent::getDescription
     * @todo   Implement testGetDescription().
     */
    public function testGetDescription()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Jsvrcek\ICS\Model\CalendarEvent::setDescription
     * @todo   Implement testSetDescription().
     */
    public function testSetDescription()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
